global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.

# A scrape configuration for the bot
scrape_configs:
  - job_name: 'inventory_bot'
    # metrics_path defaults to /metrics
    # scheme defaults to http
    static_configs:
      - targets: ['localhost:9100']